repository_description: "FastAPI based project to run commands / code on a sandbox environment."
branch_name_convention: "Use 'feat/', 'fix/', or 'chore/' prefixes."

commands:
  base_image: "ghcr.io/astral-sh/uv"
  install_dependencies: "uv sync"
  format_code: "uv run ruff check . --fix; uv run ruff format .; uv run pyproject-fmt pyproject.toml"