repository_description: "FastAPI based project to run commands / code on a sandboxed environment."
branch_name_convention: "Use 'feat/', 'fix/', or 'chore/' prefixes."

commands:
  base_image: "ghcr.io/astral-sh/uv:python3.12-bookworm-slim"
  install_dependencies: "uv sync --only-group=dev"
  format_code: "uv run --only-group=dev ruff check . --fix; uv run --only-group=dev ruff format .; uv run --only-group=dev pyproject-fmt pyproject.toml"
