name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Install libomp-dev
        run: sudo apt-get install -y libomp-dev

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked

      - name: Run linting
        run: make lint

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Install libomp-dev
        run: sudo apt-get install -y libomp-dev

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked

      - name: Run Unittests
        run: make test
